CREATE TABLE conversations (
 id TEXT PRIMARY KEY,
 anonymous_user_id TEXT NOT NULL,
 create_request_id TEXT NOT NULL,
 version INTEGER NOT NULL DEFAULT 1 CHECK(version>=1),
 status TEXT NOT NULL CHECK(status IN ('active','paused','resuming','ended')),
 end_reason TEXT CHECK(end_reason IN ('user_end','setup_cancel','background_timeout','max_duration','transport_failure','abandoned')),
 resume_attempt_id TEXT REFERENCES live_sessions(id) DEFERRABLE INITIALLY DEFERRED,
 created_at INTEGER NOT NULL,
 first_provider_dispatch_at INTEGER,
 first_interpreter_observed_at INTEGER,
 last_product_activity_received_at INTEGER,
 paused_at INTEGER,
 resume_expires_at INTEGER,
 ended_at INTEGER,
 product_deadline_at INTEGER,
 app_version TEXT NOT NULL,
 conversation_policy_version TEXT NOT NULL,
 policy_json TEXT NOT NULL CHECK(json_valid(policy_json)),
 UNIQUE(anonymous_user_id,create_request_id),
 CHECK((status='ended')=(ended_at IS NOT NULL)),
 CHECK((status='ended')=(end_reason IS NOT NULL)),
 CHECK((status='resuming')=(resume_attempt_id IS NOT NULL))
) STRICT;
CREATE TABLE live_sessions (
 id TEXT PRIMARY KEY,
 conversation_id TEXT NOT NULL REFERENCES conversations(id),
 generation INTEGER NOT NULL CHECK(generation>=1),
 openai_session_id TEXT UNIQUE,
 state TEXT NOT NULL CHECK(state IN ('creating','active','closing','closed','failed','unknown')),
 initial_mode TEXT NOT NULL CHECK(initial_mode IN ('setup','interpreter')),
 start_reason TEXT NOT NULL CHECK(start_reason IN ('initial','bootstrap_replacement','resume')),
 request_fingerprint TEXT,
 request_conversation_version INTEGER,
 resume_claimed_at INTEGER,
 resume_claim_expires_at INTEGER,
 resume_claim_version INTEGER,
 resume_outcome TEXT CHECK(resume_outcome IN ('pending','committed','aborted','expired')),
 model TEXT NOT NULL,
 transport TEXT NOT NULL CHECK(transport='webrtc'),
 prompt_version TEXT NOT NULL,
 app_version TEXT NOT NULL,
 creation_requested_at INTEGER NOT NULL,
 provider_request_dispatched_at INTEGER,
 creation_completed_at INTEGER,
 handoff_ack_deadline_at INTEGER,
 handoff_acknowledged_at INTEGER,
 cleanup_requested_at INTEGER,
 cleanup_reason TEXT CHECK(cleanup_reason IN ('response_not_received','primary_startup_failed','abandoned_connect','hidden','user_end','cancelled','replacement','server_shutdown','client_disconnected','handoff_timeout','handoff_not_activatable','resume_claim_expired')),
 cleanup_attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(cleanup_attempt_count>=0),
 cleanup_last_attempt_at INTEGER,
 cleanup_next_attempt_at INTEGER,
 cleanup_retry_expires_at INTEGER,
 cleanup_retry_exhausted_at INTEGER,
 cleanup_last_result TEXT CHECK(cleanup_last_result IN ('closed_observed','terminal_not_live','retryable_error','blocked_auth_config')),
 cleanup_last_error_code TEXT CHECK(length(cleanup_last_error_code)<=64),
 cleanup_blocked_at INTEGER,
 provider_started_observed_at INTEGER,
 interpreter_ready_observed_at INTEGER,
 provider_expires_at INTEGER,
 lease_id TEXT,
 lease_expires_at INTEGER,
 lease_released_at INTEGER,
 close_requested_at INTEGER,
 closed_observed_at INTEGER,
 last_report_received_at INTEGER,
 close_confirmed INTEGER NOT NULL DEFAULT 0 CHECK(close_confirmed IN (0,1)),
 close_confirmation_source TEXT CHECK(close_confirmation_source IN ('browser','sideband')),
 provider_close_reason TEXT CHECK(length(provider_close_reason) BETWEEN 1 AND 256),
 provider_close_reason_source TEXT CHECK(provider_close_reason_source IN ('browser','sideband')),
 app_end_reason TEXT CHECK(app_end_reason IN ('user_end','setup_cancel','background_timeout','max_duration','transport_failure','abandoned','media_not_ready','provider_creation_failed','webrtc_failed','restore_ack_failed','hidden','claim_timeout','interrupted_by_restart')),
 provider_checkpoint_seconds REAL CHECK(provider_checkpoint_seconds>=0 AND provider_checkpoint_seconds<=1.7976931348623157e308),
 provider_final_seconds REAL CHECK(provider_final_seconds>=0 AND provider_final_seconds<=1.7976931348623157e308),
 provider_checkpoint_source TEXT CHECK(provider_checkpoint_source IN ('browser','sideband')),
 provider_final_source TEXT CHECK(provider_final_source IN ('browser','sideband')),
 usage_conflict INTEGER NOT NULL DEFAULT 0 CHECK(usage_conflict IN (0,1)),
 usage_conflict_details TEXT CHECK(length(usage_conflict_details)<=1024),
 observed_wall_ms INTEGER CHECK(observed_wall_ms>=0),
 setup_ms INTEGER CHECK(setup_ms>=0),
 active_interpreter_ms INTEGER CHECK(active_interpreter_ms>=0),
 visible_paused_ms INTEGER CHECK(visible_paused_ms>=0),
 last_checkpoint_at_interpreter_ready REAL,
 last_checkpoint_received_at INTEGER,
 estimated_total_seconds REAL CHECK(estimated_total_seconds>=0),
 estimate_method_version TEXT,
 estimate_as_of INTEGER,
 measurement_version TEXT,
 activity_report_seq INTEGER CHECK(activity_report_seq>=0),
 accepted_source_speech_ms INTEGER CHECK(accepted_source_speech_ms>=0),
 completed_source_speech_ms INTEGER CHECK(completed_source_speech_ms>=0),
 speech_measurement_version TEXT,
 speech_measurement_status TEXT CHECK(speech_measurement_status IN ('complete','partial','unavailable')),
 app_metrics_finalized INTEGER NOT NULL DEFAULT 0 CHECK(app_metrics_finalized IN (0,1)),
 metrics_json TEXT CHECK(json_valid(metrics_json)),
 usage_quality TEXT NOT NULL DEFAULT 'unknown' CHECK(usage_quality IN ('final','partial','unknown','conflict')),
 pricing_policy_version TEXT,
 UNIQUE(conversation_id,generation),
 CHECK((cleanup_requested_at IS NULL)=(cleanup_reason IS NULL)),
 CHECK((close_confirmed=0)=(close_confirmation_source IS NULL)),
 CHECK((provider_close_reason IS NULL)=(provider_close_reason_source IS NULL)),
 CHECK((provider_checkpoint_seconds IS NULL)=(provider_checkpoint_source IS NULL)),
 CHECK((provider_final_seconds IS NULL)=(provider_final_source IS NULL)),
 CHECK(completed_source_speech_ms IS NULL OR (accepted_source_speech_ms IS NOT NULL AND completed_source_speech_ms<=accepted_source_speech_ms)),
 CHECK((start_reason='resume')=(resume_outcome IS NOT NULL))
) STRICT;
CREATE INDEX conversations_owner_created ON conversations(anonymous_user_id,created_at);
CREATE INDEX conversations_expiry ON conversations(status,resume_expires_at);
CREATE INDEX sessions_conversation_created ON live_sessions(conversation_id,creation_requested_at);
CREATE INDEX sessions_reservations ON live_sessions(state,lease_expires_at);
CREATE INDEX sessions_resume_expiry ON live_sessions(resume_outcome,resume_claim_expires_at);
CREATE INDEX sessions_cleanup_due ON live_sessions(cleanup_next_attempt_at,cleanup_requested_at,id) WHERE cleanup_requested_at IS NOT NULL;
CREATE INDEX sessions_handoff_due ON live_sessions(handoff_ack_deadline_at) WHERE handoff_acknowledged_at IS NULL;
CREATE UNIQUE INDEX one_progressing_session ON live_sessions(conversation_id) WHERE state IN ('creating','active','closing');
